### ISSUE TITLE
Checklist for final deployment

### ISSUE THREAD

**Issue by rossant** [cortex-lab/alyx#305]
* [x] Test locally recovering database from SQL or JSON backups
* [x] Make a final static dump
* [x] Test locally
* [x] Upload the static dump to cone
* [x] On cone, update the git repo of alyx and alyx-dev
* [x] Make a final total_reset
* [x] Disable total_reset in production
* [x] `./manage.py check --deploy`
* [x] Log error messages in a file
* [x] Disable DEBUG in django settings
* [ ] Disable non-secure http version of alyx
* [x] Put the google sheets in read-only mode

**Comment by rossant** [comment]
@nsteinme may I disable the non-secure http version of alyx now?

**Comment by nsteinme** [comment]
Yes I think so - I believe everyone has updated. Thanks -
