### ISSUE TITLE
Move implant weight to surgery model

### ISSUE THREAD

**Issue by k1o0** [cortex-lab/alyx#835]
- [x] Add implant_weight field to Surgery model (+ve float, non-nullable, blank).
- [x] Modify water control model to subtract last surgery implant weight from each weighing.
- [x] Modify water restriction admin view to show non-editable implant weights. 
- [x] Add migration to remove implant weight from Subject model; copy implant weight to subject JSON field.
- [x] Run script to move implant weight values to first headplate implant surgery or to first surgery.
- [x] Deploy to cortexlab Alyx dev
- [x] Deploy to production
